// Backend API compatibility layer for self-hosted mode.
// Re-exports from backendClient.js which calls the Deno backend.

export {
  generateImage,
  generateI2I,
  decomposeLayers,
  generateVideo,
  generateI2V,
  generateMarketingStudioAd,
  processV2V,
  processRecast,
  processLipSync,
  generateAudio,
  uploadFile,
  getUserBalance,
  getHistory,
  deleteMedia,
  getModelById,
  getVideoModelById,
  getI2IModelById,
  getI2VModelById,
  getV2VModelById,
  getRecastModelById,
  getLipSyncModelById,
  getAudioModelById,
  registerAppInterest,
  getAppInterests,
  runClipping,
  runMotionGraphics,
  runMotionGraphicsEdit,
} from './backendClient.js';
